name: CI test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo test